### ISSUE TITLE
"block future dates" doesn't block from entering future time

### ISSUE THREAD

**Issue by vasanthid** [PredixDev/px-datetime-picker#2]
When using
block-future-dates="true" with px-datetime-picker, it doesn't block user from typing in future time.

When future time is entered, it doesn't throw any error.

**Comment by benoitjchevalier** [comment]
Hi,

just tried it on the demo page and using "block-future-date" lead to the datetime picker to throw an error message when selecting a future date.

Could you reproduce in a jsfiddle or describe the steps you've taken to reproduce?

Cheers,
Ben

**Comment by vasanthid** [comment]
It works fine for the "date" component, but not for the "time"component.

Now, the current time is 08/23/16  2:08PM.

With "block-future-dates" set to "true", 
I can still enter 08/23/16  3:08PM  (future hour)

It doesn't throw error.

**Comment by vasanthid** [comment]
![image](https://cloud.githubusercontent.com/assets/15004965/17909883/570ec03e-693b-11e6-8bda-014a64ec9907.png)

**Comment by benoitjchevalier** [comment]
Thanks for clarifying, I missed the fact that this only applied at the time level.

Unfortunately this is a shortcoming/design of the validation process, the block future/past date only apply at a "day" granularity at the moment.

Improving the validation to include time might not be straightforward due to timezones issue (validation for date and time are done separately, so time doesn't know what the currently selected date is).

There might be different way we could get around it (blockFutureTime, allow dev to choose granularity over the blocking, improving validation...).

**Comment by Raafee** [comment]
as per some requirement we need to block future date and past date should be allowed user to select up to one year past date is it possible can we achieve with this component. if not can you add

**Comment by benoitjchevalier** [comment]
Please open a separate issue/enhancement request

**Comment by randyaskin** [comment]
Block future dates / past dates now works with both date and time in latest version of all datetime components.
